export interface VhUsados {
  id : number;
  idlote : number;
  usu : string;
  consignacion : string;
  retoma : string;
  otros : string;
  placa : string;
  interno : string;
  asesor : string;
  sala : string;
  fecha : Date;
  hora : string; //?
  marca : string;
  referencia : string;
  modelo : string;
  combustible :  number | boolean | null;
  km : string;
  transmision : number | boolean | null;
  color : string;
  cilindraje : string;
  traccion : string;
  cojineria : string;
  linea : string;
  porcllantadelizq : number;
  porcllantadelder : number;
  porcllantatraizq : number;
  porcllantatrader : number;
  marcallantadelizq : string;
  marcallantadelder : string;
  marcallantatraizq : string;
  marcallantatrader : string;
  porcrep : number;
  marcarep : string;
  porcrindelizq : number;
  porcrindelder : number;
  porcrintraizq : number;
  porcrintrader : number;
  taparindelizq : string;
  taparindelder : string;
  taparintraizq : string;
  taparintrader : string;
  marcarindelizq : string;
  marcarindelder : string;
  marcarintraizq : string;
  marcarintrader : string;
  porcrinrep : number;
  taparinrep : string;
  marcarinrep : string;
  matricula : number | boolean | null;
  soat : number | boolean | null;
  rtm : number | boolean | null;
  notas : string;
  incllave : number | boolean | null;
  increpllave : number | boolean | null;
  incmanual : number | boolean | null;
  incencendedor : number | boolean | null;
  inccruceta : number | boolean | null;
  incllave_tipo1 : number | boolean | null;
  incllave_tipo2 : number | boolean | null;
  incgato : number | boolean | null;
  inckith : number | boolean | null;
  incantena : number | boolean | null;
  incmaletero : number | boolean | null;
  nivelcombustible : string
  incbateria : number | boolean | null;
  incradio : number | boolean | null;
  notasdocumentos : string;
  clienteentrega : string;
  fechaentrada : Date;
  clienterecibe : string;
  fechasalida : Date;

}
